import {
  FitnessCenter,
  Spa,
  MenuBook,
  Work,
  LocalCafe,
  Nightlight,
  DirectionsRun,
  Psychology,
  Palette,
  School,
  FlashOn
} from '@mui/icons-material';

export const habitTemplates = [
  {
    id: 'morning_meditation',
    name: 'Morning Meditation',
    description: 'Start your day with mindfulness and clarity',
    icon: Spa,
    category: 'Spirit',
    difficulty: 'Easy',
    frequency: 'Daily',
    targetCompletions: 1,
    color: '#9c27b0',
    tags: ['wellness', 'mindfulness', 'morning'],
    popular: true
  },
  {
    id: 'daily_exercise',
    name: 'Daily Exercise',
    description: 'Move your body and stay healthy',
    icon: FitnessCenter,
    category: 'Body',
    difficulty: 'Medium',
    frequency: 'Daily',
    targetCompletions: 1,
    color: '#f44336',
    tags: ['fitness', 'health', 'energy'],
    popular: true
  },
  {
    id: 'read_30_minutes',
    name: 'Read 30 Minutes',
    description: 'Expand your knowledge and imagination',
    icon: MenuBook,
    category: 'Mind',
    difficulty: 'Easy',
    frequency: 'Daily',
    targetCompletions: 1,
    color: '#2196f3',
    tags: ['learning', 'knowledge', 'growth'],
    popular: true
  },
  {
    id: 'drink_water',
    name: 'Drink 8 Glasses of Water',
    description: 'Stay hydrated throughout the day',
    icon: LocalCafe,
    category: 'Body',
    difficulty: 'Easy',
    frequency: 'Daily',
    targetCompletions: 8,
    color: '#00bcd4',
    tags: ['health', 'hydration', 'wellness'],
    popular: false
  },
  {
    id: 'sleep_8_hours',
    name: 'Sleep 8 Hours',
    description: 'Prioritize rest and recovery',
    icon: Nightlight,
    category: 'Body',
    difficulty: 'Medium',
    frequency: 'Daily',
    targetCompletions: 1,
    color: '#673ab7',
    tags: ['health', 'recovery', 'energy'],
    popular: false
  },
  {
    id: 'morning_run',
    name: 'Morning Run',
    description: 'Cardio exercise to start your day',
    icon: DirectionsRun,
    category: 'Body',
    difficulty: 'Medium',
    frequency: 'Daily',
    targetCompletions: 1,
    color: '#ff5722',
    tags: ['fitness', 'cardio', 'morning'],
    popular: true
  },
  {
    id: 'journaling',
    name: 'Daily Journaling',
    description: 'Reflect on your thoughts and experiences',
    icon: Psychology,
    category: 'Mind',
    difficulty: 'Easy',
    frequency: 'Daily',
    targetCompletions: 1,
    color: '#795548',
    tags: ['reflection', 'mindfulness', 'growth'],
    popular: false
  },
  {
    id: 'creative_project',
    name: 'Creative Project',
    description: 'Work on your creative skills',
    icon: Palette,
    category: 'Creative',
    difficulty: 'Medium',
    frequency: 'Daily',
    targetCompletions: 1,
    color: '#e91e63',
    tags: ['creativity', 'art', 'expression'],
    popular: false
  },
  {
    id: 'learn_new_skill',
    name: 'Learn New Skill',
    description: 'Dedicate time to personal growth',
    icon: School,
    category: 'Mind',
    difficulty: 'Hard',
    frequency: 'Daily',
    targetCompletions: 1,
    color: '#ff9800',
    tags: ['learning', 'growth', 'development'],
    popular: true
  },
  {
    id: 'focused_work',
    name: 'Focused Work Session',
    description: 'Deep work without distractions',
    icon: Work,
    category: 'Mind',
    difficulty: 'Medium',
    frequency: 'Daily',
    targetCompletions: 1,
    color: '#607d8b',
    tags: ['productivity', 'focus', 'career'],
    popular: false
  },
  {
    id: 'yoga_practice',
    name: 'Yoga Practice',
    description: 'Improve flexibility and mindfulness',
    icon: Spa,
    category: 'Body',
    difficulty: 'Easy',
    frequency: 'Daily',
    targetCompletions: 1,
    color: '#4caf50',
    tags: ['flexibility', 'mindfulness', 'wellness'],
    popular: true
  },
  {
    id: 'practice_gratitude',
    name: 'Practice Gratitude',
    description: 'Write down three things you\'re grateful for',
    icon: Psychology,
    category: 'Spirit',
    difficulty: 'Easy',
    frequency: 'Daily',
    targetCompletions: 3,
    color: '#ff9800',
    tags: ['gratitude', 'positivity', 'mindfulness'],
    popular: false
  },
  {
    id: 'take_vitamins',
    name: 'Take Daily Vitamins',
    description: 'Support your health with essential nutrients',
    icon: LocalCafe,
    category: 'Body',
    difficulty: 'Easy',
    frequency: 'Daily',
    targetCompletions: 1,
    color: '#795548',
    tags: ['health', 'nutrition', 'wellness'],
    popular: false
  },
  {
    id: 'stretch_breaks',
    name: 'Hourly Stretch Breaks',
    description: 'Take short breaks to stretch and move',
    icon: FitnessCenter,
    category: 'Body',
    difficulty: 'Easy',
    frequency: 'Daily',
    targetCompletions: 8,
    color: '#2196f3',
    tags: ['movement', 'health', 'productivity'],
    popular: false
  },
  {
    id: 'no_sugar',
    name: 'No Sugar Challenge',
    description: 'Avoid added sugars for better health',
    icon: LocalCafe,
    category: 'Body',
    difficulty: 'Hard',
    frequency: 'Daily',
    targetCompletions: 1,
    color: '#f44336',
    tags: ['health', 'nutrition', 'discipline'],
    popular: true
  },
  {
    id: 'code_practice',
    name: 'Daily Code Practice',
    description: 'Improve programming skills with exercises',
    icon: Work,
    category: 'Mind',
    difficulty: 'Medium',
    frequency: 'Daily',
    targetCompletions: 1,
    color: '#607d8b',
    tags: ['coding', 'skills', 'development'],
    popular: false
  },
  {
    id: 'language_learning',
    name: 'Language Learning',
    description: 'Practice a new language for 15 minutes',
    icon: School,
    category: 'Mind',
    difficulty: 'Medium',
    frequency: 'Daily',
    targetCompletions: 1,
    color: '#00bcd4',
    tags: ['languages', 'learning', 'communication'],
    popular: false
  },
  {
    id: 'digital_detox',
    name: 'Digital Detox Hour',
    description: 'Disconnect from screens for one hour',
    icon: Nightlight,
    category: 'Spirit',
    difficulty: 'Medium',
    frequency: 'Daily',
    targetCompletions: 1,
    color: '#673ab7',
    tags: ['digital', 'mindfulness', 'balance'],
    popular: false
  },
  {
    id: 'meal_planning',
    name: 'Weekly Meal Planning',
    description: 'Plan healthy meals for the week',
    icon: LocalCafe,
    category: 'Body',
    difficulty: 'Medium',
    frequency: 'Weekly',
    targetCompletions: 1,
    color: '#4caf50',
    tags: ['nutrition', 'planning', 'health'],
    popular: false
  },
  {
    id: 'breathing_exercises',
    name: 'Breathing Exercises',
    description: 'Practice deep breathing for stress relief',
    icon: Spa,
    category: 'Spirit',
    difficulty: 'Easy',
    frequency: 'Daily',
    targetCompletions: 2,
    color: '#9c27b0',
    tags: ['breathing', 'stress', 'relaxation'],
    popular: false
  },
  {
    id: 'declutter_space',
    name: 'Daily Decluttering',
    description: 'Organize one area of your living space',
    icon: Work,
    category: 'Mind',
    difficulty: 'Easy',
    frequency: 'Daily',
    targetCompletions: 1,
    color: '#ff9800',
    tags: ['organization', 'minimalism', 'productivity'],
    popular: false
  },
  {
    id: 'cold_shower',
    name: 'Cold Shower Challenge',
    description: 'Take cold showers for mental toughness',
    icon: LocalCafe,
    category: 'Body',
    difficulty: 'Hard',
    frequency: 'Daily',
    targetCompletions: 1,
    color: '#2196f3',
    tags: ['discipline', 'health', 'mental'],
    popular: true
  },
  {
    id: 'walk_break',
    name: 'Afternoon Walk Break',
    description: 'Take a 15-minute walk to refresh',
    icon: DirectionsRun,
    category: 'Body',
    difficulty: 'Easy',
    frequency: 'Daily',
    targetCompletions: 1,
    color: '#4caf50',
    tags: ['movement', 'nature', 'energy'],
    popular: false
  },
  {
    id: 'mindful_eating',
    name: 'Mindful Eating',
    description: 'Eat slowly and focus on your food',
    icon: LocalCafe,
    category: 'Spirit',
    difficulty: 'Medium',
    frequency: 'Daily',
    targetCompletions: 3,
    color: '#ff9800',
    tags: ['mindfulness', 'nutrition', 'health'],
    popular: false
  }
];

export const communityTemplates = [
  {
    id: 'community_1',
    name: '30-Day Fitness Challenge',
    description: 'Complete workout routine for 30 consecutive days',
    icon: FitnessCenter,
    category: 'Body',
    difficulty: 'Hard',
    frequency: 'Daily',
    targetCompletions: 1,
    color: '#ff5722',
    tags: ['fitness', 'challenge', 'strength'],
    popular: true,
    author: 'FitGuru23',
    likes: 342
  },
  {
    id: 'community_2',
    name: 'Morning Routine Mastery',
    description: 'Build the perfect morning routine for productivity',
    icon: FlashOn,
    category: 'Mind',
    difficulty: 'Medium',
    frequency: 'Daily',
    targetCompletions: 3,
    color: '#ffc107',
    tags: ['morning', 'productivity', 'routine'],
    popular: true,
    author: 'ProductivityPro',
    likes: 256
  },
  {
    id: 'community_3',
    name: 'Digital Detox Evening',
    description: 'Disconnect from screens 1 hour before bed',
    icon: Nightlight,
    category: 'Mind',
    difficulty: 'Easy',
    frequency: 'Daily',
    targetCompletions: 1,
    color: '#9c27b0',
    tags: ['wellness', 'sleep', 'digital'],
    popular: false,
    author: 'MindfulLife',
    likes: 128
  },
  {
    id: 'community_4',
    name: 'Weekend Warrior Workout',
    description: 'Intensive weekend training sessions',
    icon: FitnessCenter,
    category: 'Body',
    difficulty: 'Hard',
    frequency: 'Weekly',
    targetCompletions: 2,
    color: '#f44336',
    tags: ['fitness', 'weekend', 'intensity'],
    popular: true,
    author: 'GymBeast',
    likes: 189
  },
  {
    id: 'community_5',
    name: 'Mindful Minute Breaks',
    description: 'Take 1-minute mindfulness breaks throughout the day',
    icon: Spa,
    category: 'Spirit',
    difficulty: 'Easy',
    frequency: 'Daily',
    targetCompletions: 10,
    color: '#4caf50',
    tags: ['mindfulness', 'breaks', 'stress'],
    popular: false,
    author: 'ZenMaster',
    likes: 94
  },
  {
    id: 'community_6',
    name: 'Creative Writing Sprint',
    description: 'Write 500 words daily for creative expression',
    icon: Palette,
    category: 'Creative',
    difficulty: 'Medium',
    frequency: 'Daily',
    targetCompletions: 1,
    color: '#e91e63',
    tags: ['writing', 'creativity', 'daily'],
    popular: true,
    author: 'WriteDaily',
    likes: 267
  },
  {
    id: 'community_7',
    name: 'Learning Hour Power',
    description: 'Dedicate one hour to learning new skills',
    icon: School,
    category: 'Mind',
    difficulty: 'Medium',
    frequency: 'Daily',
    targetCompletions: 1,
    color: '#2196f3',
    tags: ['learning', 'skills', 'education'],
    popular: false,
    author: 'LearnAddict',
    likes: 156
  },
  {
    id: 'community_8',
    name: 'Nutrition Reset Week',
    description: 'Clean eating challenge for one week',
    icon: LocalCafe,
    category: 'Body',
    difficulty: 'Hard',
    frequency: 'Weekly',
    targetCompletions: 7,
    color: '#ff9800',
    tags: ['nutrition', 'clean', 'challenge'],
    popular: true,
    author: 'HealthCoach',
    likes: 312
  },
  {
    id: 'community_9',
    name: 'Productivity Block System',
    description: 'Work in focused 25-minute blocks',
    icon: Work,
    category: 'Mind',
    difficulty: 'Medium',
    frequency: 'Daily',
    targetCompletions: 8,
    color: '#607d8b',
    tags: ['productivity', 'focus', 'pomodoro'],
    popular: false,
    author: 'FocusExpert',
    likes: 203
  },
  {
    id: 'community_10',
    name: 'Gratitude Photo Journal',
    description: 'Take one photo daily of something you\'re grateful for',
    icon: Psychology,
    category: 'Spirit',
    difficulty: 'Easy',
    frequency: 'Daily',
    targetCompletions: 1,
    color: '#795548',
    tags: ['gratitude', 'photography', 'daily'],
    popular: false,
    author: 'PhotoLife',
    likes: 87
  },
  {
    id: 'community_11',
    name: 'Stretching Routine',
    description: '10-minute full body stretching session',
    icon: DirectionsRun,
    category: 'Body',
    difficulty: 'Easy',
    frequency: 'Daily',
    targetCompletions: 1,
    color: '#00bcd4',
    tags: ['stretching', 'flexibility', 'daily'],
    popular: false,
    author: 'FlexLife',
    likes: 145
  },
  {
    id: 'community_12',
    name: 'Language Immersion',
    description: 'Immerse yourself in a new language for 30 minutes',
    icon: School,
    category: 'Mind',
    difficulty: 'Medium',
    frequency: 'Daily',
    targetCompletions: 1,
    color: '#673ab7',
    tags: ['language', 'immersion', 'daily'],
    popular: true,
    author: 'PolyglotPro',
    likes: 298
  },
  {
    id: 'community_13',
    name: 'Meditation Journey',
    description: 'Progressive meditation program for beginners',
    icon: Spa,
    category: 'Spirit',
    difficulty: 'Easy',
    frequency: 'Daily',
    targetCompletions: 2,
    color: '#9c27b0',
    tags: ['meditation', 'beginner', 'progressive'],
    popular: false,
    author: 'MeditateDaily',
    likes: 178
  },
  {
    id: 'community_14',
    name: 'Code Review Practice',
    description: 'Review one pull request daily',
    icon: Work,
    category: 'Mind',
    difficulty: 'Medium',
    frequency: 'Daily',
    targetCompletions: 1,
    color: '#ff5722',
    tags: ['coding', 'review', 'daily'],
    popular: false,
    author: 'CodeReviewer',
    likes: 134
  },
  {
    id: 'community_15',
    name: 'Hydration Challenge',
    description: 'Drink water every hour during waking hours',
    icon: LocalCafe,
    category: 'Body',
    difficulty: 'Easy',
    frequency: 'Daily',
    targetCompletions: 12,
    color: '#00bcd4',
    tags: ['hydration', 'challenge', 'health'],
    popular: false,
    author: 'HydrationHero',
    likes: 167
  },
  {
    id: 'community_16',
    name: 'Reading Marathon',
    description: 'Read 20 pages daily from any book',
    icon: MenuBook,
    category: 'Mind',
    difficulty: 'Easy',
    frequency: 'Daily',
    targetCompletions: 1,
    color: '#4caf50',
    tags: ['reading', 'books', 'daily'],
    popular: true,
    author: 'BookWorm',
    likes: 289
  },
  {
    id: 'community_17',
    name: 'Art Sketch Daily',
    description: 'Create one sketch or drawing daily',
    icon: Palette,
    category: 'Creative',
    difficulty: 'Medium',
    frequency: 'Daily',
    targetCompletions: 1,
    color: '#e91e63',
    tags: ['art', 'sketching', 'daily'],
    popular: false,
    author: 'SketchDaily',
    likes: 198
  },
  {
    id: 'community_18',
    name: 'Morning Affirmations',
    description: 'Practice positive self-talk every morning',
    icon: Psychology,
    category: 'Spirit',
    difficulty: 'Easy',
    frequency: 'Daily',
    targetCompletions: 5,
    color: '#ff9800',
    tags: ['affirmations', 'positive', 'morning'],
    popular: false,
    author: 'PositiveVibes',
    likes: 112
  }
];
